package inits;

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;

// Generated 2016-12-20 14:40:02 by Hibernate Tools 3.4.0.CR1

/**
 * College generated by hbm2java
 */
public class College implements java.io.Serializable {

	private long collegeid;
	private String collegename;
	@JsonIgnore
	private Set<Userinfo> userinfo = new HashSet<Userinfo>();

	public Set<Userinfo> getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Set<Userinfo> userinfo) {
		this.userinfo = userinfo;
	}

	public College() {
	}

	public College(long collegeid) {
		this.collegeid = collegeid;
	}

	public College(long collegeid, String collegename) {
		this.collegeid = collegeid;
		this.collegename = collegename;
	}

	public long getCollegeid() {
		return this.collegeid;
	}

	public void setCollegeid(long collegeid) {
		this.collegeid = collegeid;
	}

	public String getCollegename() {
		return this.collegename;
	}

	public void setCollegename(String collegename) {
		this.collegename = collegename;
	}


	
	

}
