package inits;



// Generated 2016-12-21 16:13:20 by Hibernate Tools 3.4.0.CR1

/**
 * UserinfoTeacher generated by hbm2java
 */

public class UserinfoTeacher implements java.io.Serializable {

	private UserinfoTeacherId id;

	public UserinfoTeacher() {
	}

	public UserinfoTeacher(UserinfoTeacherId id) {
		this.id = id;
	}

	public UserinfoTeacherId getId() {
		return this.id;
	}

	public void setId(UserinfoTeacherId id) {
		this.id = id;
	}

}
