package inits;

// Generated 2016-12-20 14:40:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;  
/**
 * Userinfo generated by hbm2java
 */
/*@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)  */
public class Userinfo implements java.io.Serializable {

	private long userid;
	private String username;
	private String userpassword;
	private Date createtime;
	private Long collegeid;
	private College college;
	/*private Set<Teacher> teacher;*/

	public Userinfo() {
	}

	public Userinfo(long userid) {
		this.userid = userid;
	}

	public Userinfo(long userid, String username, String userpassword,
			Date createtime, Long collegeid) {
		this.userid = userid;
		this.username = username;
		this.userpassword = userpassword;
		this.createtime = createtime;
		this.collegeid = collegeid;
	}

	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Long getCollegeid() {
		return this.collegeid;
	}

	public void setCollegeid(Long collegeid) {
		this.collegeid = collegeid;
	}

	public College getCollege() {
		return college;
	}

	public void setCollege(College college) {
		this.college = college;
	}

/*	public Set<Teacher> getTeacher() {
		return teacher;
	}

	public void setTeacher(Set<Teacher> teacher) {
		this.teacher = teacher;
	}*/

	
}
