package inits;

// Generated 2016-12-21 16:10:42 by Hibernate Tools 3.4.0.CR1

/**
 * UserinfoTeacherId generated by hbm2java
 */
public class UserinfoTeacherId implements java.io.Serializable {

	private Long userid;
	private Long teacherid;

	public UserinfoTeacherId() {
	}

	public UserinfoTeacherId(Long userid, Long teacherid) {
		this.userid = userid;
		this.teacherid = teacherid;
	}

	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	public Long getTeacherid() {
		return this.teacherid;
	}

	public void setTeacherid(Long teacherid) {
		this.teacherid = teacherid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserinfoTeacherId))
			return false;
		UserinfoTeacherId castOther = (UserinfoTeacherId) other;

		return ((this.getUserid() == castOther.getUserid()) || (this
				.getUserid() != null && castOther.getUserid() != null && this
				.getUserid().equals(castOther.getUserid())))
				&& ((this.getTeacherid() == castOther.getTeacherid()) || (this
						.getTeacherid() != null
						&& castOther.getTeacherid() != null && this
						.getTeacherid().equals(castOther.getTeacherid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result
				+ (getTeacherid() == null ? 0 : this.getTeacherid().hashCode());
		return result;
	}

}
